version: "3.1"

services:
  postgresql:
    image: "pgtest:633d1d-062166"
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: "${PG_PASSWORD}"
  keycloak:
    image: "bitnami/keycloak:22.0.4-debian-11-r3"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_PASSWORD: "${PG_PASSWORD}"