version: "3.1"

services:
  postgresql:
    image: "pgtest:d41d8c-747090"
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: "${PG_PASSWORD}"
  keycloak:
    image: "bitnami/keycloak:22.0.4-debian-11-r3"
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_DATABASE_PASSWORD: "${PG_PASSWORD}"
  dormyboba-auth:
    image: "dormyboba-auth:bbf8ca-881240"
    ports:
      - "8082:8082"
