FROM mcr.microsoft.com/devcontainers/base:bullseye
RUN apt update && \
  apt install -y python3.9 python3-pip
USER vscode
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN ${HOME}/.local/bin/poetry config virtualenvs.in-project true
