@startuml Component diagram for dormyboba project
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam defaultFontName Open Sans

Container(registerPage, "Register Webpage", "html", "Static html page with Telegram Login Widget")
Container(telegramBot, "Telegram Bot", "python", "Telegram bot interface")

Container_Boundary(botBackend, "Bot Backend") {
  Component(registerController, "Register Controller", "", "Provides functionality related to registration. Returns register HTML page and handles data-onauth POST request")
  Component(botComponent, "Bot Component", "", "Handles commands from user")
  Component(userService, "User service", "", "Provides functionality related to user management, i.e. registration and retrieving user information")
  Component(mailService, "Mail service", "", "Provides mailing functionality")
  Component(apiComponent, "API Component", "", "Provides access to Telegram API")
}

Boundary(dataStore, "DataStore") {
  ContainerDb(db, "Database", "MongoDB", "Stores user info and invalidated secrets")
}

Rel_D(registerPage, registerController, "Send user info")
Rel_U(registerController, registerPage, "Send registration view")

Rel_D(registerController, userService, "Write user info")
Rel_D(botComponent, userService, "Manage users")
Rel_D(botComponent, mailService, "Mailing")

Rel_D(telegramBot, botComponent, "Send commands")

Rel_D(userService, db, "Read and write user info")
Rel_D(userService, apiComponent, "Get info about user and manipulate groups")

Rel_D(mailService, apiComponent, "Send message")
@enduml