@startuml System diagram for dormyboba project
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam defaultFontName Open Sans

Person(studentA, "Student A", "A student")
Person(councilMemA, "CouncilMem A", "A student council member")

Container(registerPage, "Register Webpage", "html", "Static html page with login options")
Container(vkBot, "Vk Bot", "", "Vk bot interface")

System_Boundary(backend, "Backend") {
  Container(apiService, "API Service", "Python", "MVP for handling non-VK actions (e.g. serve allowMessages widget)")
  Container(vkBotService, "Vk Bot Service", "Python", "Handles Vk updates and performs logic")
  ContainerDb(db, "Database", "PostgreSQL", "Stores user and group info")
}

Rel_D(studentA, registerPage, "Performs registration")
Rel_D(councilMemA, vkBot, "Initiates registration")

Rel_D(apiService, db, "")
Rel_D(registerPage, apiService, "Sends user info")
Rel_D(vkBot, vkBotService, "Sends Vk updates")

Rel_D(vkBotService, db, "CRUD")
@enduml