name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: alpine-3.18

    steps:
    - uses: actions/checkout@v3

    - name: Build kroki image
      run: make image-builder
